apiVersion: v1
kind: Secret

metadata:
  name: streamlit-secrets

type: Opaque

stringData:
  secrets.toml: |
    [postgres]
    drivername = "postgresql"
    host = "postgres"
    port = 5432
    database = "f1db"
    username = "postgres"
    password = "postgres"

